---
- name: Install and enable apache
  hosts: all
  become: yes

  vars:
    package_name: apache2  # adapt to your distribution

  tasks:

    - name: Make sure apache is installed
      package:
        name: "{{ package_name }}"
        state: present

    - name: Make sure apache is active on boot and started
      service:
        name: "{{ package_name }}"
        enabled: true
        state: started
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
