- hosts: webapps
  remote_user: ubuntu
  become: true
  tasks:
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present
  - name: Start Apache2 server
    service:
      name: apache2
      state: started
      enabled: True
  - name: Deploy static website
    copy:
      src: index.html
      dest: /var/www/html/
